export { Pa11yDefaultOptionInterface } from './pa11y.default.option.interface'
export { ResultsInterface } from './results.interface'
export { ReporterOptionInterface } from './reporter.option.interface'
export { SitemapInterface } from './sitemap.interface'
export { UrlSitemapInterface } from './url.sitemap.interface'
export { Pa11yOptionsInterface } from './pa11y.options.interface'
export { AccessibilityTestFileInterface } from './accessibility.test.file.interface'
